package com.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.user_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.user_id
     *
     * @return the value of news.user_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.user_id
     *
     * @param userId the value for news.user_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setContent(String content) {
        this.content = content;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param userName the value for news.content
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}