package com.model;

public class Room {
    private String allname;//用于选择框
    private String floorName;

    public String getFloorName() {
        return floorName;
    }

    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }

    private String customerName;

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }





    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.floor_id
     *
     * @mbggenerated
     */
    private Integer floorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.house
     *
     * @mbggenerated
     */
    private String house;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.standard
     *
     * @mbggenerated
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.info
     *
     * @mbggenerated
     */
    private String info;

    private String customer_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.floor_id
     *
     * @return the value of room.floor_id
     * @mbggenerated
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.floor_id
     *
     * @param floorId the value for room.floor_id
     * @mbggenerated
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.name
     *
     * @return the value of room.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.name
     *
     * @param name the value for room.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.house
     *
     * @return the value of room.house
     * @mbggenerated
     */
    public String getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.house
     *
     * @param house the value for room.house
     * @mbggenerated
     */
    public void setHouse(String house) {
        this.house = house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.unit
     *
     * @return the value of room.unit
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.unit
     *
     * @param unit the value for room.unit
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.standard
     *
     * @return the value of room.standard
     * @mbggenerated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.standard
     *
     * @param standard the value for room.standard
     * @mbggenerated
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.info
     *
     * @return the value of room.info
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.info
     *
     * @param info the value for room.info
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info;
    }





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.photo
     *
     * @return the value of room.photo
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.photo
     *
     * @param photo the value for room.photo
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.customer_id
     *
     * @mbggenerated
     */
    public String getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id;
    }

    public String getAllname() {
        return allname;
    }

    public void setAllname(String allname) {
        this.allname = allname;
    }



}