package com.model;

import java.util.Date;

public class Complain {
    private String roomName;
    private String complainstatus;

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    private String customerName;

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.id
     *
     * @mbggenerated
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.create_time
     *
     * @mbggenerated
     */
    private Date createTime;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.customer_id
     *
     * @mbggenerated
     */
    private String customer_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.id
     *
     * @return the value of complain.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.id
     *
     * @param id the value for complain.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.create_time
     *
     * @return the value of complain.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.create_time
     *
     * @param createTime the value for complain.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.customer_id
     *
     * @return the value of complain.customer_id
     *
     * @mbggenerated
     */
    public String getCustomer_id() {
        return customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.customer_id
     *
     * @param customer_id the value for complain.customer_id
     *
     * @mbggenerated
     */
    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.info
     *
     * @return the value of complain.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.info
     *
     * @param info the value for complain.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain.title
     *
     * @return the value of complain.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain.title
     *
     * @param title the value for complain.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getComplainstatus() {
        return complainstatus;
    }

    public void setComplainstatus(String complainstatus) {
        this.complainstatus = complainstatus;
    }

}