package com.model;

public class Floor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor.del
     *
     * @mbggenerated
     */
    private String del;

    private String addressLat;
    private String  addressLon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.id
     *
     * @return the value of floor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.id
     *
     * @param id the value for floor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.name
     *
     * @return the value of floor.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.name
     *
     * @param name the value for floor.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.info
     *
     * @return the value of floor.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.info
     *
     * @param info the value for floor.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor.del
     *
     * @return the value of floor.del
     *
     * @mbggenerated
     */
    public String getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor.del
     *
     * @param del the value for floor.del
     *
     * @mbggenerated
     */
    public void setDel(String del) {
        this.del = del;
    }


    public String getAddressLat() {
        return addressLat;
    }

    public void setAddressLat(String addressLat) {
        this.addressLat = addressLat;
    }

    public String getAddressLon() {
        return addressLon;
    }

    public void setAddressLon(String addressLon) {
        this.addressLon = addressLon;
    }
}