package com.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer id;

    private String genderName;

    public String getGenderName() {
        return genderName;
    }

    public void setGenderName(String genderName) {
        this.genderName = genderName;
    }

    private String deptName;


    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String account;

    private String nationalName;

    private String educationName;

    public String getNationalName() {
        return nationalName;
    }

    public void setNationalName(String nationalName) {
        this.nationalName = nationalName;
    }

    public String getEducationName() {
        return educationName;
    }

    public void setEducationName(String educationName) {
        this.educationName = educationName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String password;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.number
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dept_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telphone
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card_no
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.national_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer nationalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.education_id
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private Integer educationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.institute
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String institute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.major
     *
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    private String major;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setPassword(String password) {
        this.password = password;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.number
     *
     * @return the value of user.number
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.number
     *
     * @param number the value for user.number
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dept_id
     *
     * @return the value of user.dept_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dept_id
     *
     * @param deptId the value for user.dept_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telphone
     *
     * @return the value of user.telphone
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telphone
     *
     * @param telphone the value for user.telphone
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_card_no
     *
     * @return the value of user.id_card_no
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_card_no
     *
     * @param idCardNo the value for user.id_card_no
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.national_id
     *
     * @return the value of user.national_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.national_id
     *
     * @param nationalId the value for user.national_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setNationalId(Integer nationalId) {
        this.nationalId = nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.education_id
     *
     * @return the value of user.education_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public Integer getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.education_id
     *
     * @param educationId the value for user.education_id
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setEducationId(Integer educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.institute
     *
     * @return the value of user.institute
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.institute
     *
     * @param institute the value for user.institute
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setInstitute(String institute) {
        this.institute = institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.major
     *
     * @return the value of user.major
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.major
     *
     * @param major the value for user.major
     * @mbg.generated Wed Apr 11 20:22:07 CST
     */
    public void setMajor(String major) {
        this.major = major;
    }


}